package edu.handong.csee.java.lab07.prob2;
/**
 * @author s0rrow
 * This class is for declaring methods needed for 
 */
public class Chicken { 
	private String name;// Declare string variable for name.
	private double price;// Declare double variable for price.
	private int stars;// Declare integer variable for rating.

	public Chicken() {// This method is for initializing the variables.
		this.name = "";// Initialize string variable name from this class as an empty string.
		this.price = 0.0;// Initialize double variable price from this class to 0.
		this.stars = 0;// Initialize integer variable stars from this class to 0.
	}

	public Chicken(String name, double price, int stars) {// This method is for assigning given parameters to local variables.
		this.name = name;// Assign given string to local string variable.
		this.price = price;// Assign given double to local double variable.
		this.stars = stars;// Assign given integer to local integer variable.
	}

	public String get_name() {// A getter method generated by Eclipse.
		return this.name;// Get string variable name from this class.
	}

	public double get_price() {// A getter method generated by Eclipse.
		return this.price;// Get double variable price from this class.
	}

	public int get_stars() {// A getter method generated by Eclipse.
		return this.stars;// Get integer variable stars from this class.
	}

	public void set_name(String name) {// A setter method generated by Eclipse.
		this.name = name;// Set string variable name from this class.
	}

	public void set_price(double price) {// A setter method generated by Eclipse.
		this.price = price;// Set double variable price from this class.
	}

	public void set_stars(int stars) {// A setter method generated by Eclipse.
		this.stars = stars;// Set integer variable stars from this class.
	}
}
