package edu.handong.csee.java.lab07.prob3;
/**
 * @author s0rrow
 * This class is for offer methods to main class.
 */
public class Attendance {
	private String name;// Declare local string variable.
	private int year;// Declare local integer variable.
	private String student_id;// Declare local string variable.
	private int missed;// Declare local integer variable.

	public Attendance() {// This method is for initializing each variables from this class.
		this.name = "Null";// Initiate string variable from this class.
		this.year = 0;// Initiate integer variable from this class.
		this.student_id = "Null";// Initiate string variable from this class.
		this.missed = 0;// Initiate integer variable from this class.
	}

	public Attendance(String name, int year, String student_id, int missed) {// This method is for assigning given parameters to variables.
		this.name = name;// Assign string parameter to string variable from this class.
		this.year = year;// Assign int parameter to int variable from this class.
		this.student_id = student_id;// Assign int parameter to int variable from this class.
		this.missed = missed;// Assign int parameter to int variable from this class.
	}

	public String get_name() {// This is a getter method generated by Eclipse.
		return name;// Get string variable name and return it.
	}

	public int get_year() {// This is a getter method generated by Eclipse.
		return year;// Get integer variable year and return it.
	}

	public String get_id() {// This is a getter method generated by Eclipse.
		return student_id;// Get integer variable student_id and return it.
	}

	public int get_missed() {// This is a getter method generated by Eclipse.
		return missed;// Get integer variable missed and return it.
	}

	public void set_name(String name) {// This is a setter method generated by Eclipse.
		this.name = name;// Set string variable name from this class and return it.
	}

	public void set_year(int year) {// This is a setter method generated by Eclipse.
		this.year = year;// Set integer variable year from this class and return it.
	}

	public void set_id(String student_id) {// This is a setter method generated by Eclipse.
		this.student_id = student_id;// Set integer variable student_id from this class and return it.
	}

	public void set_missed(int missed) {// This is a setter method generated by Eclipse.
		this.missed = missed;// Set integer variable missed from this class and return it.
	}

}
